version: '2'

services:
  crowi:
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      - MATHJAX=1
    command: npm start
    ports:
      - 80:3000
    volumes:
      - ./crowi_data/:/data/
      - ./entrypoint.sh:/entrypoint.sh
    links:
      - mongo:db
      - redis:redis
      - es:es

  mongo:
    image: mongo
    volumes:
      - ./mongodb_data/db:/data/db

  redis:
    image: redis:alpine

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      # パスワードの入力を省略するためX-Packを切る
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # プラグインのKuromojiが必要
    entrypoint:
      - bash
      - -c
      - >-
        elasticsearch-plugin list | grep -q analysis-kuromoji
        || elasticsearch-plugin install analysis-kuromoji
        && exec $$0 $$@
    command:
      - /bin/bash
      - bin/es-docker