version: '2'

services:
  crowi:
    build: 
      context: .
      dockerfile: docker/crowi.Dockerfile
    environment: 
      - MATHJAX=1
    command: npm start
    ports:
      - 80:3000
    volumes:
      - ./crowi_data/:/data/
      - ./entrypoint.sh:/entrypoint.sh
    links:
      - mongo:db
      - redis:redis
      - es:es

  mongo:
    image: mongo
    volumes:
      - ./mongodb_data/db:/data/db

  redis:
    image: redis:alpine

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    memswap_limit: 1g
    # プラグインのKuromojiが必要
    entrypoint:
      - bash
      - -c
      - >-
        elasticsearch-plugin list | grep -q analysis-kuromoji
        || elasticsearch-plugin install analysis-kuromoji
        && exec $$0 $$@
    command:
      - /bin/bash
      - bin/es-docker

  backup:
    build: 
      context: .
      dockerfile: docker/backup.Dockerfile
      args:
        - awscli_version=1.11.130
    environment: 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./backup/mongodb.repo:/etc/yum.repos.d/mongodb.repo
      - ./backup/s3_dump_upload.sh:/s3_dump_upload.sh
      - ./backup/crontab:/var/spool/cron/crontabs/root
    links:
      - mongo:db
